services:
  - type: web
    name: instagram-365-poster-web
    runtime: python
    plan: free
    buildCommand: "./automation/render_build.sh"
    startCommand: "gunicorn automation.app:app"
    envVars:
      - key: PORT
        value: 10000


